---

- project:
    check:
      jobs:
        - oslo.versionedobjects-src-grenade-multinode
        - oslo.versionedobjects-nova-tox-py314
        - oslo.versionedobjects-ironic-tox-py314
    gate:
      jobs:
        - oslo.versionedobjects-nova-tox-py314
        - oslo.versionedobjects-ironic-tox-py314
    templates:
      - check-requirements
      - lib-forward-testing-python3
      - openstack-python3-jobs
      - openstack-python3-next-jobs
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3

- job:
    name: oslo.versionedobjects-nova-tox-py314
    parent: openstack-tox-py314
    description: |
      Run cross-project unit tests on nova.
    vars:
      zuul_work_dir: src/opendev.org/openstack/nova
    required-projects:
      - openstack/nova
      - openstack/oslo.versionedobjects
    irrelevant-files: &irrelevant-files
      - ^\.gitignore$
      - ^\.gitreview$
      - ^.*\.rst$
      - ^doc/.*$
      - LICENSE
      - ^releasenotes/.*$
      - ^\.pre-commit-config\.yaml$
      - ^oslo_versionedobjects/tests/.*$
      - ^test-requirements\.txt$

- job:
    name: oslo.versionedobjects-ironic-tox-py314
    parent: openstack-tox-py314
    description: |
      Run cross-project unit tests on ironic.
    vars:
      zuul_work_dir: src/opendev.org/openstack/ironic
    required-projects:
      - openstack/ironic
      - openstack/oslo.versionedobjects
    irrelevant-files: *irrelevant-files

- job:
    name: oslo.versionedobjects-src-grenade-multinode
    parent: grenade-multinode
    voting: false
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$
      - ^.git.*$
      - ^.*/locale/.*po$
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
      - ^\.pre-commit-config\.yaml$
    required-projects:
      - opendev.org/openstack/oslo.versionedobjects
