- project:
    check:
      jobs:
        - oslo.versionedobjects-src-grenade-multinode
    templates:
      - check-requirements
      - lib-forward-testing-python3
      - openstack-lower-constraints-jobs
      - openstack-python3-victoria-jobs
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3

- job:
    name: oslo.versionedobjects-src-grenade-multinode
    parent: grenade-multinode
    voting: false
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
    required-projects:
      - opendev.org/openstack/oslo.versionedobjects
