[tox]
minversion = 3.18.0
envlist = py3,pep8

[testenv]
deps =
  -c{env:TOX_CONSTRAINTS_FILE:https://releases.openstack.org/constraints/upper/master}
  -r{toxinidir}/requirements.txt
  -r{toxinidir}/test-requirements.txt
commands = stestr run --slowest {posargs}

[testenv:pep8]
description =
  Run style checks.
deps =
  pre-commit>=2.6.0 # MIT
  {[testenv:mypy]deps}
commands =
  pre-commit run -a
  {[testenv:mypy]commands}

[testenv:mypy]
description =
  Run type checks.
deps =
  {[testenv]deps}
  mypy
  typing-extensions
  types-netaddr
commands =
  mypy --cache-dir="{envdir}/mypy_cache" -p oslo_versionedobjects {posargs}

[testenv:venv]
commands = {posargs}

[testenv:cover]
commands = python setup.py test --coverage --coverage-package-name=oslo_versionedobjects --testr-args='{posargs}'

[testenv:docs]
allowlist_externals = rm
deps =
  -c{env:TOX_CONSTRAINTS_FILE:https://releases.openstack.org/constraints/upper/master}
  -r{toxinidir}/doc/requirements.txt
commands =
  rm -fr doc/build
  sphinx-build -W --keep-going -b html doc/source doc/build/html

[testenv:releasenotes]
allowlist_externals = rm
deps = {[testenv:docs]deps}
commands =
  rm -rf releasenotes/build
  sphinx-build -a -E -W -d releasenotes/build/doctrees --keep-going -b html releasenotes/source releasenotes/build/html

[flake8]
# We only enable the hacking (H) checks
select = H
builtins = _
exclude=.venv,.git,.tox,dist,doc,*lib/python*,*egg,build

[hacking]
import_exceptions =
  collections.abc
  types
  typing
  typing_extensions
  oslo_versionedobjects._i18n
